name: "Build and Deploy"

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch that triggered the workflow.
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install
        run: npm install

      # Run your build step
      - name: Build
        run: npm run build

      # Deploy using `demurgos/ga-deploy-git`
      - name: Deploy
        uses: demurgos/ga-deploy-git@v1
        with:
          # Personnal access token with `public_repo` or `repo` permission (required)
          # It is defined in the `ACCESS_TOKEN` secret.
          accessToken: ${{ secrets.ACCESS_TOKEN }}
          # Directory containing the build artifact to deploy (default: repo root)
          srcDir: build
          # Destination branch (required)
          destBranch: gh-pages
